# Generated by Django 3.0.8 on 2020-09-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_bids_comment_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='Bidding',
            field=models.ManyToManyField(blank=True, related_name='Bids', to='auction.listing'),
        ),
        migrations.AlterField(
            model_name='bids',
            name='Start_Bid',
            field=models.IntegerField(max_length=100),
        ),
    ]
