# Generated by Django 3.0.8 on 2020-09-16 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_auto_20200915_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='Imgae_Url',
            new_name='Image_Url',
        ),
    ]
