# Generated by Django 3.0.8 on 2020-09-16 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_auto_20200915_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='Image_Url',
            new_name='ImageUrl',
        ),
    ]
