# Generated by Django 3.0.8 on 2020-09-16 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_auto_20200915_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2020, 9, 15, 23, 58, 42, 861933)),
        ),
    ]
