# Generated by Django 3.0.8 on 2020-09-16 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0009_auto_20200916_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2020, 9, 16, 1, 45, 1, 20313)),
        ),
    ]
