# Generated by Django 3.0.8 on 2020-09-17 22:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0012_auto_20200917_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='List_Creator',
            field=models.CharField(default='Admin', max_length=500),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2020, 9, 17, 15, 28, 20, 70913)),
        ),
    ]
