# Generated by Django 3.0.8 on 2020-09-17 23:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0013_auto_20200917_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2020, 9, 17, 16, 32, 4, 295568)),
        ),
    ]
