# Generated by Django 3.0.8 on 2020-09-18 03:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0014_auto_20200917_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='watch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=50)),
                ('ImageUrl', models.CharField(max_length=100000)),
                ('Image', models.ImageField(default='/static/auction/img/icon-3.png', upload_to='')),
                ('Category', models.CharField(max_length=10000)),
                ('Bid', models.IntegerField(default=0)),
                ('Time', models.TimeField(default=datetime.datetime(2020, 9, 17, 20, 26, 48, 642595))),
                ('List_Creator', models.CharField(default='Admin', max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='listing',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2020, 9, 17, 20, 26, 48, 633532)),
        ),
    ]
