# Generated by Django 3.0.8 on 2020-09-20 05:54

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0015_auto_20200917_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='User_Bid',
            field=models.ManyToManyField(blank=True, related_name='User_Bid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2020, 9, 19, 22, 54, 2, 720055)),
        ),
        migrations.AlterField(
            model_name='watch',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2020, 9, 19, 22, 54, 2, 720055)),
        ),
    ]
