# Generated by Django 3.0.8 on 2020-09-20 06:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0016_auto_20200919_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2020, 9, 19, 23, 0, 51, 281672)),
        ),
        migrations.AlterField(
            model_name='watch',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2020, 9, 19, 23, 0, 51, 281672)),
        ),
    ]
