# Generated by Django 3.0.8 on 2020-09-21 08:36

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0018_auto_20200921_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='User_Bid',
            field=models.ManyToManyField(blank=True, related_name='User_Bidings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2020, 9, 21, 1, 36, 39, 205411)),
        ),
        migrations.AlterField(
            model_name='watch',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2020, 9, 21, 1, 36, 39, 209400)),
        ),
    ]
