# Generated by Django 3.0.8 on 2020-09-22 05:00

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0019_auto_20200921_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='User_Comment',
            field=models.ManyToManyField(blank=True, related_name='Comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2020, 9, 21, 22, 0, 49, 652831)),
        ),
        migrations.AlterField(
            model_name='watch',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2020, 9, 21, 22, 0, 49, 652831)),
        ),
    ]
