# Generated by Django 3.0.8 on 2020-09-22 05:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0020_auto_20200921_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Comment_By',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='List_Creator',
            field=models.CharField(default='Anonymous', max_length=500),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2020, 9, 21, 22, 41, 32, 894713)),
        ),
        migrations.AlterField(
            model_name='watch',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2020, 9, 21, 22, 41, 32, 894713)),
        ),
    ]
