# Generated by Django 3.0.8 on 2020-09-22 05:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0021_auto_20200921_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='List_Comment',
            field=models.ManyToManyField(blank=True, related_name='Comment_For_Listing', to='auction.listing'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2020, 9, 21, 22, 49, 53, 223821)),
        ),
        migrations.AlterField(
            model_name='watch',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2020, 9, 21, 22, 49, 53, 239441)),
        ),
    ]
