# Generated by Django 3.0.8 on 2020-09-23 05:44

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0023_auto_20200922_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2020, 9, 22, 22, 44, 18, 362518)),
        ),
        migrations.AlterField(
            model_name='watch',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2020, 9, 22, 22, 44, 18, 362518)),
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Notifications', models.CharField(max_length=1000)),
                ('User_To_Be_Notified', models.ManyToManyField(blank=True, related_name='User_To_Be_Notified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
